### ISSUE TITLE
Palette description of PaletteMax

### ISSUE THREAD

**Issue by Michel-0** [SpongePowered/Schematic-Specification#10]
While PaletteMax sais "**Specifies the size of the block palette _in number of bytes_ needed for the maximum palette index.**", Palette sais "**The maximum index cannot be greater than PaletteMax - 1.**", which makes no sense.

The maximum index cannot be greather than **2^(8 * PaletteMax) - 1**.

**Comment by skairunner** [comment]
Seconding. It seems that in practice (e.g. [WorldEdit](https://github.com/EngineHub/WorldEdit/blob/master/worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/SpongeSchematicWriter.java#L180)) PaletteMax is `the max index of the palette object`, not `the number of bytes required to specify the max index`. Issuing a correction to the spec would probably help people who are trying to write files that will interoperate with other tools already in the ecosystem.

**Comment by gabizou** [comment]
This is fixed by not requiring the palette max as an explicit field in v3
