### ISSUE TITLE
Shouldn't "Data Version" field in version 2 be "DataVersion"?

### ISSUE THREAD

**Issue by tech4me** [SpongePowered/Schematic-Specification#15]
I think there is an extra space in the field name. The issue exist on line 84 and 178 in schematic-2.md.
In WorldEdit "DataVersion" is being used instead of "Data Version".
https://github.com/EngineHub/WorldEdit/blob/master/worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/SpongeSchematicReader.java

**Comment by Turidus** [comment]
Agreed, I did run in the same problem.
Would also make the naming of Data Version consistent with all other fields.

**Comment by JasonYuan869** [comment]
Created PR #18 for this.

**Comment by gabizou** [comment]
Merged in https://github.com/SpongePowered/Schematic-Specification/commit/59efd30da5edf2ccab75f6f96288f847e8fc1a91
