### ISSUE TITLE
Compression Explanation

### ISSUE THREAD

**Issue by meyerzinn** [SpongePowered/Schematic-Specification#2]
@Deamon5550 went insane and came up with a genius compression technique. Here's how it works:
1. Determine the number of bits per block by using `ceil(lg(PalleteLength))` (where lg is log in base 2).
2. For every element in the BlockData array, get it's binary form (padded to take up the number of bits specified by step 1) and append it to the result. Pad the final byte to be a complete 8 bits.
3. Finally, for every byte of the result of step 2, get the hex representation of the byte and append it to a new array, the final one.

I made a little helper with the Desmos Calculator [here](https://www.desmos.com/calculator/yjnfvdpohb) (https://www.desmos.com/calculator/yjnfvdpohb)

Examples:

Given a palette with a length of 2, we use 1 bit per entry. Let's say we have `[0,0,1,1,0,0,1,0]` as our BlockData. As you can see, the final array is `[0x32]`. Magic!

```
+-------------------+      +----------+      +----+    +--------+
|                   |      |          |      |    |    |        |
| [0,0,1,1,0,0,1,0] +----> | 00110010 +----> | 50 +--> | [0x32] |
|                   |      |          |      |    |    |        |
+-------------------+      +----------+      +----+    +--------+

```

Now, to decompress this format. Let's take example 1's result, `[0x32]`. You'll notice in step 3 of this process I had to add the padding back. I added a pipe to show you exactly where that occurred. Basically, for step 4, I just had to split the binary apart because the PaletteLength was 2, so the bits per entry was 1.

```
+--------+       +----+       +-----------+       +-------------------+
|        |       |    |       |           |       |                   |
| [0x32] | +---> | 50 | +---> | 00|110010 | +---> | [0,0,1,1,0,0,1,0] |
|        |       |    |       |           |       |                   |
+--------+       +----+       +-----------+       +-------------------+
```

Let's assume a palette size of 300, mandating 9 bits per entry.You'll notice I padded all entries to take up 9 bits. Interestingly enough, the encoded version is larger than the original. The effect of the encoding is not obvious with small samples.

```
+-------------+       +----------------------------------------+       +-------------------+       +-----------------------+
|             |       |                                        |       |                   |       |                       |
| [295,119,5] | +---> | 10010011 1|0011101 11|000000 101|00000 | +---> | [147,157,192,160] | +---> | [0x93,0x9D,0xC0,0xA0] |
|             |       |                                        |       |                   |       |                       |
+-------------+       +----------------------------------------+       +-------------------+       +-----------------------+
```

**Comment by Deamon5550** [comment]
cool story bro?....is there an issue in this or can I close it?

**Comment by meyerzinn** [comment]
I’m going to be putting it as a PR but for now I wanted to list it as an issue. Feel free to close it.
