### ISSUE TITLE
The description of a varint seems wrong

### ISSUE THREAD

**Issue by mortie** [SpongePowered/Schematic-Specification#21]
The description of varints in the spec is:

> Each integer is bitpacked into a single byte with [varint](https://en.wikipedia.org/wiki/Variable-length_code) encoding. The first byte determines the length of the integer with a maximum length of 5 (for a 32 bit number), and depending on the length, each proceeding byte is or'ed and current value bit shifted by the length multiplied by 7. Examples can be found with Sponge's implementation for [retreving data](https://github.com/SpongePowered/SpongeCommon/blob/aa2c8c53b4f9f40297e6a4ee281bee4f4ce7707b/src/main/java/org/spongepowered/common/data/persistence/SchematicTranslator.java#L147-L175) and [storing data](https://github.com/SpongePowered/SpongeCommon/blob/aa2c8c53b4f9f40297e6a4ee281bee4f4ce7707b/src/main/java/org/spongepowered/common/data/persistence/SchematicTranslator.java#L230-L251).

I find this description kind of confusing. But what's clear is that there's some kind of length-prefixed encoding, where the first byte specifies the length of the variable length integer.

That doesn't seem to be the case though, since the linked source code seems to implement the [variable-length quantity](https://en.wikipedia.org/wiki/Variable-length_quantity) style of varint (base 128, where the most significant bit is used to mark continuation bytes). The wikipedia link also doesn't make it clear, because that link goes to the page for variable length codes in general, not to the page about VLQ in particular.

**Comment by gabizou** [comment]
Please review #20 as it makes a clearer definition of varint.
