### ISSUE TITLE
Palette is no array?

### ISSUE THREAD

**Issue by Michel-0** [SpongePowered/Schematic-Specification#8]
I don't see the reason, why is Palette no array.

Imagine i want the block at X, Y, Z (relative), so my index is BlockData[x + z * Width + y * Width * Length].
How may i now pick out this specific element out of the palette?
I need to loop through it until i find it! It makes way more sense to me to sort by the index, so you can directly access the element by calculating its index.

In the end you could do it as array and don't need to save the index anyway, since you got a defined order.

**Comment by gabizou** [comment]
You shouldn't be modifying the data directly, you should have a schematic object representation to allow you to modify the block data (and thereby validating that the representative `TileEntity` data is valid for the same position).

The specification is for the storage format, not for the in-memory object representation.
